### ISSUE TITLE
facter_cacheable: undefined method `exist' for Puppet::FileSystem:Module

### ISSUE THREAD

**Issue by dzeleski** [waveclaw/puppet-facter_cacheable#6]
After upgrading to puppet 2017.3 from 2016.4.3 I am getting the following error during a puppet run: 
```
Failed to load feature test for facter_cacheable: undefined method `exist' for Puppet::FileSystem:Module
Did you mean?  exist?
```

I assume this is an issue with the newer version of ruby that is being used with this version of puppet.

**Comment by waveclaw** [comment]
Yes, the newer version of Ruby deprecated `.exist()` and now newer code has to use the `exist?()` method.

Doing this will also drop support for Puppet 2 and Puppet older released of Puppet Enterprise using Puppet 3.

**Comment by dzeleski** [comment]
@waveclaw We are on puppet 4. Im using 0.2.0 from the forge: `mod 'waveclaw/facter_cacheable', '0.2.0'`

**Comment by waveclaw** [comment]
This was updated in 0.2.1 for setting the Puppet Feature when not on windows.  The function is not used elsewhere.

**Comment by dzeleski** [comment]
Tested, confirmed it fixes that error. TY!
